apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${containername}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${containername}
  template:
    metadata:
      labels:
        app: ${containername}
    spec:
      containers:
        - name: ${containername}
          image: ghcr.io/moutansos/${containername}:${buildid}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HOST
              value: 0.0.0.0
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: ${containername}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ${containername}
  type: ClusterIP